a = [1,25,116,48,96,75,15,355,4,9]
print(a)
print("Append adds a element in last")
a.append(48)
print("List after append is: ",a)
print("Sorting the list")
a.sort(reverse=True)
print("Sorted list in reverse manner: ",a)
print("Reversing a list")
a.reverse()
print("List after reversal: ",a)
print("Display the index of given number")
print("Index of 25 is: ",a.index(25))
